main/urls.py
from django.urls import path  
from . import views

app_name = 'main' 

urlpatterns = [
	path('',views.index,name='index'),
	path('list/',views.list,name='list'),
	path('product/<int:pid>',views.product,name='product'),
]

transmax/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

class Product(models.Model):
	name    = models.TextField('Название продукта')
	link    = models.TextField('Ссылка')
	count   = models.IntegerField('Проданное количество')
	price   = models.IntegerField('Цена')
	income  = models.BigIntegerField('Прибыль')
	created_at  = models.DateTimeField(auto_now_add=True)
	updated_at  = models.DateTimeField(auto_now = True)

	def __str__(self):
		return self.name
class ArchiveIncome(models.Model):
	archive_parent   = models.ForeignKey(Product, on_delete=models.CASCADE) 
	archive_count    = models.IntegerField()
	archive_bill     = models.BigIntegerField()
	archive_income   = models.BigIntegerField('Прибыль')
	archive_increase = models.IntegerField()	
	archive_income_increase = models.IntegerField()	
	archive_created_at  = models.DateTimeField(auto_now_add = True)
	
	def __str__(self):
		return self.archive_bill
		
class TotalIncome(models.Model):
	date  = models.DateTimeField(auto_now_add = True)
	sales = models.IntegerField()
	bill  = models.BigIntegerField()

main/views.py
from django.shortcuts import render, get_object_or_404
import datetime
from .models import Product, TotalIncome,ArchiveIncome
def index(request):
	week_day = datetime.datetime.now().isocalendar()[2]
	start_date = datetime.datetime.now() - datetime.timedelta(days = week_day)
	dates = [str((start_date+datetime.timedelta(days=i)).date()) for i in range(8)]
	dates = dates[1:]
	totals = TotalIncome.objects.all().order_by('-id')
	difference = totals[0].bill - totals[len(totals)-1].bill
	changes = ArchiveIncome.objects.all().order_by('-id')
	return render(request,'main/index.html',{'days':dates,'totals':totals,'changes':changes,'difference':difference})
def list(request):
	products_list = Product.objects.all().order_by('-count')
	return render(request,'main/list.html',{'products_list':products_list})
def product(request,pid):
	week_day = datetime.datetime.now().isocalendar()[2]
	start_date = datetime.datetime.now() - datetime.timedelta(days = week_day)
	dates = [str((start_date+datetime.timedelta(days=i)).date()) for i in range(8)]
	dates = dates[1:]
	products = get_object_or_404(Product, pk=pid)
	product_changes = products.archiveincome_set.all()
	return render(request,'main/product.html',{'product':products,'product_changes':product_changes,'days':dates})

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Графики с использованием chart.js</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.0/chart.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
</head>
<body>
    <div class="container">
        <div class="header">
            <a href="{% url 'main:index' %}">Главная</a>
            <a href="{% url 'main:list' %}">Список продуктов</a>        
        </div>
        <center><h1>Статистика дохода</h1></center>
        <div class="table c3">
            <div class="table_header">
                <div class="table_header_item">Дата обновления статистики</div>
                <div class="table_header_item">Общее кол.во продаж</div>
                <div class="table_header_item">Общий доход</div>
            </div>
            <div class="table_items">
                {% for total in totals %}
                    <div class="table_item">
                        <div class="column date">{{ total.date }}</div>
                        <div class="column">{{ total.sales }}</div>
                        <div class="column">{{ total.bill }}</div>
                    </div>
                {% endfor %}
            </div>
            <div class="table_items">
                    <div class="table_item">
                        <div class="column"></div>
                        <div class="column"></div>
                        <div class="column total_result">Рост +{{ difference }}</div>
                    </div>
            </div>
        </div>
        <center><h1>Изменения в продожах</h1></center>
        <div class="table">
            <div class="table_header">
                <div class="table_header_item">Продукт</div>
                <div class="table_header_item">Продажи</div>
                <div class="table_header_item">Цена</div>
                <div class="table_header_item">Доход</div>
            </div>
            <div class="table_items">
                {% for prod in changes %}
                    <div class="table_item">
                        <div class="column"><a href="{% url 'main:product' prod.archive_parent.id %}">{{ prod.archive_parent.name }}</a></div>
                        <div class="column">{{ prod.archive_count }} <sup><span>(+{{ prod.archive_increase }})</span></sup></div>
                        <div class="column">{{ prod.archive_bill }}</div>
                        <div class="column">{{ prod.archive_income }} <sup><span>(+{{ prod.archive_income_increase }})</span></sup></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
<script>
    result = document.querySelector('.total_result')
    dates = document.querySelectorAll('.date')
    date_1 = dates[0]
    date_2 = dates[dates.length - 1]
    text = "Рост прибыли от "+date_2.innerHTML+" до "+date_1.innerHTML+": <span>+"+{{ difference }}+"$</span>"
    result.innerHTML = text
</script>
<script>
    // Получение ссылки на элемент canvas в DOM
    const $grafica = document.querySelector("#grafica");
    // Tags - это метки, которые идут по оси X.  
    const tags = {{ days|safe }};
    // У нас может быть несколько наборов данных. Давайте начнем с одного
    const dataSales2020 = {
        label: "Статистика дохода",
        data: [648366, 548378, 348458], // Данные представляют собой массив, который должен иметь такое же количество значений, как и количество тегов.
        backgroundColor: 'transparent', // Цвет фона
        borderColor: 'rgba(54, 162, 235, 1)', // Цвет границ
        borderWidth: 1,// Толщина границ
    };
    const dataSales2021 = {
        label: "Продажи за lty,",
        data: [3000, 3000, 6854, 1354], // Данные представляют собой массив, который должен иметь такое же количество значений, как и количество тегов.
        backgroundColor: 'rgba(54, 162, 235, 0.2)', // Цвет фона
        borderColor: 'rgba(0, 0, 0, 1)', // Цвет границ
        borderWidth: 1,// Толщина границ
    };
    new Chart($grafica, {
        type: 'line',// Тип графики
        data: {
            labels: tags,
            datasets: [
                dataSales2020,
            ]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }],
            },
        }
    });
</script>
</body>

</html>

main/templates/main/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="{% static 'css/styles.css'%}">
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
</head>
<body>
	<div class="container">
		<div class="header">
			<a href="{% url 'main:index' %}">Главная</a>
			<a href="{% url 'main:list' %}">Список продуктов</a>		
		</div>
		<div class="dld">
				<div class="download">
					<a href="{% static 'excell/data.xlsx'%}">Скачать отчет <i class="fa fa-download" aria-hidden="true"></i></a>
				</div>
		</div>
		<div class="table">
			<div class="table_header">
				<div class="table_header_item">Продукт</div>
				<div class="table_header_item">Продажи</div>
				<div class="table_header_item">Цена</div>
				<div class="table_header_item">Доход</div>
			</div>
			<div class="table_items">
				{% for prod in products_list %}
					<div class="table_item">
						<div class="column"><a href="{% url 'main:product' prod.id %}">{{ prod.name }}</a> </div>
						<div class="column">{{ prod.count }}</div>
						<div class="column">{{ prod.price }}</div>
						<div class="column">{{ prod.income }}</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
</body>
</html>

main/templates/main/product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.0/chart.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
</head>
<body>
	<div class="container">
		<div class="header">
			<a href="{% url 'main:index' %}">Главная</a>
			<a href="{% url 'main:list' %}">Список продуктов</a>		
		</div>
		<div class="table">
            <div class="table_header">
                <div class="table_header_item">Продукт</div>
                <div class="table_header_item">Продажи</div>
                <div class="table_header_item">Цена</div>
                <div class="table_header_item">Доход</div>
            </div>
            <div class="table_items">
                {% for prod in product_changes %}
                    <div class="table_item">
                        <div class="column">{{ prod.archive_parent.name }}</div>
                        <div class="column">{{ prod.archive_count }} <sup><span>(+{{ prod.archive_increase }})</span></sup></div>
                        <div class="column">{{ prod.archive_bill }}</div>
                        <div class="column">{{ prod.archive_income }}</div>
                    </div>
                    {% empty %}
                    <div class="table_item">
                        <div class="column">{{ product.name  }}</div>
                        <div class="column">{{ product.count }}</div>
                        <div class="column">{{ product.price }}</div>
                        <div class="column">{{ product.income}}</div>
                    </div>
                    <div style="padding: 30px 0px;"><center><b>Именений в продаже не обнаружено.</b></center></div>
                {% endfor %}
            </div>
        </div>
	</div>
</body>
</html>